### ISSUE TITLE
msgpack.rkt about to break API

### ISSUE THREAD

**Issue by HiPhish** [wbthomason/msgpack-rpc-racket#2]
Hi, just a quick heads-up: I am planning to introduce breaking changes in the MessagePack library soon. When I wrote my Guile implementation of MessagePack I noticed that the API can be improved a bit. The changes are:

- `pack` and `unpack` will be renamed to `pack-to` and `pack-from`, `pack-to` will take the port as the first argument and the object as the second one
- There will be a new `pack` and `unpack` procedure; `pack` takes in an object and returns a byte string of packed bytes, while `unpack` takes in a byte string of packed data and returns the unpacked object
- It will be possible to pack and unpack multiple objects as once, `pack-to` and `pack` will be able to take arbitrarily many object arguments (this is the reason for specifying the port first in `pack-to`)

The first two changes will be done first together, the third one will be added later since it does not break the previous ones.

The MessagePack library is still pre-1.0, so don't want to define a new package for these changes. Incorporating them is really staight-forward: change this
~~~ racket
(pack "foo" (current-output-port))
(unpack (current-intput-port))
~~~
to
~~~ racket
(pack-to (current-output-port) "foo")
(unpack-from (current-input-port))
~~~
If you want raw bytes you can use
~~~ racket
(pack "foo")
(unpack #"\243foo")
~~~
instead of
~~~ racket
(call-with-output-bytes
  (lambda (out)
    (pack-to out "foo")))

(call-with-input-bytes #"\243foo"
  (lambda (in)
    (unpack-from in)))
~~~

**Comment by wbthomason** [comment]
Thanks for the heads-up! I'll look for the changes to land in your library, then update accordingly.

**Comment by HiPhish** [comment]
The new version is up now. It's version 0.3.0.

**Comment by wbthomason** [comment]
Thanks again for the update (and for the excellent `msgpack` library)! I've changed my code to use the new API.
